#!/usr/bin/env bash
set -Eeu -o pipefail

# R package checks
# Updated 2019-07-31.
#
# See also:
# - R CMD build --help
# - R CMD check --help
# - Travis CI recipe
#   https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
checks_dir="${SOURCE_DIR}/checks"

# Don't require suggested packages to be installed.
export _R_CHECK_FORCE_SUGGESTS_=false

# Bug fix for `Sys.timezone()` when `timedatectl` is installed.
# https://github.com/rocker-org/rocker-versioned/issues/89
export TZ="America/New_York"

# Get the package version and define the `R CMD build` tarball output.
PKG_NAME="$(grep -E "^Package:" DESCRIPTION | cut -d ' ' -f 2)"
export PKG_NAME

PKG_VERSION="$(grep -E "^Version:" DESCRIPTION | cut -d ' ' -f 2)"
export PKG_VERSION

PKG_TARBALL="${PKG_NAME}_${PKG_VERSION}.tar.gz"
export PKG_TARBALL

echo "travis_fold:start:session-info"
"${checks_dir}/session-info"
echo "travis_fold:end:session-info"

echo "travis_fold:start:lints"
"${checks_dir}/lints"
echo "travis_fold:end:lints"

echo "travis_fold:start:r-cmd-check"
"${checks_dir}/r-cmd-check"
echo "travis_fold:end:r-cmd-check"

echo "travis_fold:start:bioc-check"
"${checks_dir}/bioc-check"
echo "travis_fold:end:bioc-check"

echo "travis_fold:start:coverage"
"${checks_dir}/coverage"
echo "travis_fold:end:coverage"

rm "$PKG_TARBALL"
