#!/usr/bin/env bash
set -Eeu -o pipefail

# Copy configuration files.
# Updated 2019-07-31.

if [[ ! -d ".Rcheck" ]]
then
    >&2 printf "Error: '.Rcheck' directory is missing.\n"
    exit 1
fi

files=(
    ".Rbuildignore"
    ".gitignore"
    ".lintr"
    ".travis.yml"
    "appveyor.yml"
    "_pkgdown.yml"
)

for file in "${files[@]}"
do
    cp -nv ".Rcheck/${file}" .
done
