#!/usr/bin/env bash
set -Eeu -o pipefail

# """
# Copy configuration files.
# Updated 2019-08-01.
# """

if [[ ! -d ".Rcheck" ]]
then
    >&2 printf "Error: '.Rcheck' directory is missing.\n"
    exit 1
fi

files=(
    ".Rbuildignore"
    ".gitignore"
    ".lintr"
    ".travis.yml"
    "_pkgdown.yml"
    "appveyor.yml"
)

for file in "${files[@]}"
do
    if [[ ! -f "$file" ]]
    then
        cp -nv ".Rcheck/${file}" .
    else
        echo "$file"
    fi
done
