#!/usr/bin/env bash
set -Eeu -o pipefail

# Run dockerized R package checks.
# Updated 2019-11-01.

if [[ -z "${image:-}" ]]
then
    image="acidgenomics/basejump"
fi

if [[ -z "${tag:-}" ]]
then
    tag="latest"
fi

image="${image}:${tag}"
workdir="/Rcheck"

docker pull "$image"
docker run \
    -it \
    -e CI="${CI:-}" \
    -e GITHUB_PAT="${GITHUB_PAT:-}" \
    -e RCHECK_KEEP_IT_100="${RCHECK_KEEP_IT_100:-}" \
    -e RCHECK_SKIP_UPDATE="${RCHECK_SKIP_UPDATE:-}" \
    --volume="${PWD}:${workdir}" \
    --workdir="${workdir}" \
    "$image" \
    ".Rcheck/run-checks"
