#!/usr/bin/env bash
set -Eeu -o pipefail

# """
# Docker failure return.
# Updated 2019-10-23.
# """

env | sort
df -h | sort
ls -al

docker images

echo "Removing images."
docker system prune --all --force
docker images

df -h | sort
