#!/usr/bin/env bash
set -Eeu -o pipefail

# Run dockerized R package checks.
# Updated 2019-08-12.

if [[ -z "${image:-}" ]]
then
    image="basejump"
fi

if [[ -z "${tag:-}" ]]
then
    tag="latest"
fi

image="acidgenomics/${image}:${tag}"
workdir="/Rcheck"

docker pull "$image"
docker run \
    -it \
    -e GITHUB_PAT="$GITHUB_PAT" \
    --volume="${PWD}:${workdir}" \
    --workdir="${workdir}" \
    "$image" \
    ".Rcheck/run-checks"
