#!/usr/bin/env bash
set -Eeu -o pipefail

# Install Rcheck repo.
# Updated 2019-07-31.

source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

# Clone the repository.
rm -rf .Rcheck
git clone https://github.com/acidgenomics/Rcheck.git .Rcheck

# Copy dotfiles.
"${source_dir}/copy-dotfiles"

# Useful for debugging:
# > pwd
# > ls -al
