#!/usr/bin/env bash
set -Eeu -o pipefail

# Run R package checks.
# Updated 2019-10-30.

# See also:
# - R CMD build --help
# - R CMD check --help
# - Travis CI recipe
#   https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/
#       script/r.rb

source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
checks_dir="${source_dir}/checks"

# Don't require suggested packages to be installed.
if [[ -z "${_R_CHECK_FORCE_SUGGESTS:-}" ]]
then
    export _R_CHECK_FORCE_SUGGESTS_=false
fi

# Only enable automatic upgrades when building the Docker images.
if [[ -z "${R_REMOTES_UPGRADE:-}" ]]
then
    export R_REMOTES_UPGRADE="never"
fi

# Bug fix for 'Sys.timezone()' when timedatectl is installed.
# https://github.com/rocker-org/rocker-versioned/issues/89
if [[ -z "${TZ:-}" ]]
then
    export TZ="America/New_York"
fi

# Get the package version and define the 'R CMD build' tarball output.
PKG_NAME="$(grep -E "^Package:" DESCRIPTION | cut -d ' ' -f 2)"
export PKG_NAME

PKG_VERSION="$(grep -E "^Version:" DESCRIPTION | cut -d ' ' -f 2)"
export PKG_VERSION

PKG_TARBALL="${PKG_NAME}_${PKG_VERSION}.tar.gz"
export PKG_TARBALL

travis_fold() {
    local action="$1"
    local name="$2"
    echo -en "travis_fold:${action}:${name}\r"
}

travis_fold start session-info
echo "Session information"
"${checks_dir}/session-info"
travis_fold end session-info

travis_fold start lints
echo "Lints"
"${checks_dir}/lints"
travis_fold end lints

if [[ -z "${RCHECK_SKIP_UPDATE}" ]]
then
    travis_fold start update-deps
    echo "Update dependencies"
    "${checks_dir}/update-deps"
    travis_fold end update-deps
fi

travis_fold start r-cmd-check
echo "R CMD CHECK"
"${checks_dir}/r-cmd-check"
travis_fold end r-cmd-check

# Only run BiocCheck for Bioconductor packages.
if grep -q "biocViews" DESCRIPTION
then
    travis_fold start bioc-check
    echo "BiocCheck"
    "${checks_dir}/bioc-check"
    travis_fold end bioc-check
fi

travis_fold start coverage
echo "Coverage"
"${checks_dir}/coverage"
travis_fold end coverage

rm "$PKG_TARBALL"
