#!/usr/bin/env Rscript

# """
# BiocCheck
# Updated 2020-11-04.
#
# Run 'BiocCheck::usage()' for options.
# Set '--new-package' flag for extra verbose new package checks.
#
# Note that running 'R CMD BiocCheck' directly requires 'script/BiocCheck' to
# be installed at '/usr/lib64/R/bin'. Otherwise, can run directly using Rscript.
#
# @seealso
# - http://master.bioconductor.org/packages/devel/bioc/vignettes/BiocCheck/
#   inst/doc/BiocCheck.html
# """

options(
    error = quote(quit(status = 1L)),
    warning = quote(quit(status = 1L))
)

bioc_check <- function() {
    if (!requireNamespace("BiocCheck", quietly = TRUE)) {
        return(invisible(FALSE))
    }
    stopifnot(requireNamespace("BiocCheck"))
    BiocCheck::BiocCheck( \
        package = Sys.getenv("PKG_TARBALL"),
        `no-check-R-ver` = TRUE,
        `no-check-bioc-help` = TRUE,
        `no-check-coding-practices` = TRUE,
        `no-check-man-doc` = TRUE,
        `no-check-remotes` = TRUE,
        `no-check-version-num` = TRUE,
        `no-check-vignettes` = TRUE,
        `quit-with-status` = TRUE
    )
}

bioc_check()
