#!/usr/bin/env Rscript

## Check package lints with lintr.
## Updated 2019-09-15.

options(
    error = quote(quit(status = 1L)),
    warning = quote(quit(status = 1L))
)

## > if (!requireNamespace("lintr", quietly = TRUE)) {
## >     install.packages("lintr")
## > }

remotes::install_github(repo = "acidgenomics/lintr", upgrade = "never")

library(lintr)
lints <- lint_package(path = ".")
if (length(lints) > 0L) {
    print(lints)
    stop("Package failed lintr checks.")
}
