#!/usr/bin/env Rscript

## """
## Check package lints with lintr.
## Updated 2020-11-04.
## """

options(
    error = quote(quit(status = 1L)),
    warning = quote(quit(status = 1L))
)

check_lints <- function() {
    stopifnot(
        requireNamespace("lintr"),
        packageVersion("lintr") >= "2.0.0"
    )
    lints <- lintr::lint_package(path = ".")
    ## Current print bug in lintr:
    ## ## Error in httr::status_code(response) : object 'response' not found
    ## ## Calls: print -> print.lints -> github_comment -> <Anonymous>
    if (length(lints) > 0L) {
        print(lints)
        stop(sprintf(
            fmt = "Package failed lintr checks. %d %s detected.",
            length(lints),
            ngettext(n = length(lints), msg1 = "lint", msg2 = "lints")
        ))
    }
    invisible(TRUE)
}

check_lints()
