#!/usr/bin/env Rscript

## Check package lints with lintr.
## Updated 2019-09-18.

options(
    error = quote(quit(status = 1L)),
    warning = quote(quit(status = 1L))
)

## > if (!requireNamespace("lintr", quietly = TRUE)) {
## >     install.packages("lintr")
## > }

remotes::install_github(repo = "acidgenomics/lintr", upgrade = "never")

library(lintr)
lints <- lint_package(path = ".")

## Current print bug in lintr:
## ## Error in httr::status_code(response) : object 'response' not found
## ## Calls: print -> print.lints -> github_comment -> <Anonymous>

if (length(lints) > 0L) {
    print(lints)
    stop(sprintf(
        fmt = "Package failed lintr checks. %d %s detected.",
        length(lints),
        ngettext(n = length(lints), msg1 = "lint", msg2 = "lints")
    ))
}
