#!/usr/bin/env bash

# R CMD CHECK
# Updated 2019-08-12.

# See also:
# - https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# - https://stackoverflow.com/questions/47127594

# Build the tarball.
R CMD build . --no-build-vignettes --no-manual

# Install the package, to avoid unexpected covr check issues.
R CMD INSTALL "$PKG_TARBALL"

# Set `--as-cran` flag for extra verbose incoming package checks.
R CMD check "$PKG_TARBALL" --as-cran --ignore-vignettes --no-manual --timings
