#!/usr/bin/env Rscript

## """
## Session information.
## Updated 2020-11-04.
## """

options(
    error = quote(quit(status = 1L)),
    warning = quote(quit(status = 1L))
)

session_info <- function() {
    utils::sessionInfo()
    if (requireNamespace("sessioninfo", quietly = TRUE)) {
        sessioninfo::session_info()
    }
    invisible(TRUE)
}

session_info()
