#!/usr/bin/env Rscript

## Update packages.
## Updated 2019-08-13.

## > if (!requireNamespace("BiocManager", quietly = TRUE)) {
## >     install.packages("BiocManager")
## > }
## > BiocManager::install(update = TRUE, ask = FALSE)

## Checking for `GITHUB_PAT` here because travis-ci.org doesn't export it.
## Remember to pass any of these variables in docker run-image call.
if (
    isTRUE(nzchar(Sys.getenv("CI"))) &&
    isTRUE(nzchar(Sys.getenv("GITHUB_PAT")))
) {
    if (!requireNamespace("remotes", quietly = TRUE)) {
        install.packages("remotes")
    }
    remotes::update_packages(upgrade = "always")
}
