#!/usr/bin/env Rscript

## Update dependencies.
## Updated 2019-08-13.

options(
    error = quote(quit(status = 1L)),
    warning = quote(quit(status = 1L))
)

## Checking for `GITHUB_PAT` here because travis-ci.org doesn't export it.
## Remember to pass any of these variables in docker run-image call.
if (
    isTRUE(nzchar(Sys.getenv("CI"))) &&
    isTRUE(nzchar(Sys.getenv("GITHUB_PAT")))
) {
    if (!requireNamespace("remotes", quietly = TRUE)) {
        install.packages("remotes")
    }
    if (!requireNamespace("bb8", quietly = TRUE)) {
        remotes::install_github("acidgenomics/bb8", upgrade = "never")
    }
    message("Updating dependencies.")
    bb8::updateDeps()
} else {
    message("Skipping dependency updates.")
}
